### ISSUE TITLE
大神实现一个java 版的randomx吧

### ISSUE THREAD

**Issue by mSoftDeveloper** [maoxs2/go-randomx#1]

**Comment by c0mm4nd** [comment]
实现的目的？

如果你有需要的项目，我可以考虑免费帮忙或者收费实现。但是如果没有实际项目就没造轮子的必要。

**Comment by mSoftDeveloper** [comment]
实现的目的是公司要求的，我是所在的公司是做门罗矿池的，想做一个安卓的挖矿软件，现在xmr算法已经更新到randomx了，而且xmrig的代码只能编译出来arm64-v8a的  目前这个已经搞定了，但是xmrig无法编译armv7a的，所以看了您的代码，还在捋逻辑，go我看得有点头疼，所以看您能否帮忙实现一个java版本的，或者帮忙编译一个xmrig armv7a的so，如果您不愿意帮忙的话，收费大概要多少呢，我这边研究一下，麻烦您了

**Comment by c0mm4nd** [comment]
Maven: https://search.maven.org/artifact/uk.offtopica/randomx4j

Source Code: https://github.com/00-matt/randomx4j

**Comment by c0mm4nd** [comment]
armv7a 现在应该是没JIT支持，和x86相比收益不太行吧？

**Comment by mSoftDeveloper** [comment]
嗯  性能相比起来确实不如v8的  不过还是谢谢您啦  非常感谢
